name: Deploy to Deta

on:
  push:
    branches:
      - main
      - feature/tooling-optimization

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 #Be sure you check-out the repo first. Deta CLI needs access to the files

      - uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: 'super_duper_octo_barnacle'
          deta-project-dir: 'super_duper_octo_barnacle'
